server:
  port: 8828
  #port: 8888

spring:
  cloud:
    config:
      server:
        git :
          uri:  http://localhost:8888/gitblit-1.8.0/r/conf.git
          username: admin
          password: admin
