# cat customer.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: customer-rc
spec:
  replicas: 4
  selector:
        app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: unifier/customer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service

spec:
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 8000
  type: ClusterIP
  selector:
     app: customer