eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eurekaservice.credentials.uri:http://127.0.0.1:8761/}eureka/
      #defaultZone: ${vcap.services.eureka-service.credentials.uri:http://10.0.0.126:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
    
mongo:
  replica:
    set: 127.0.0.1:27017,127.0.0.1:27027,127.0.0.1:27037
    
zuul:
  routes:
    locationapigateway: 
      serviceId: location     
      path: /api/**

      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

  
           
#zuul.RibbonRoutingFilter.route.disable=true

#archaius.configurationSource.defaultFileName 
#archaius:
  #configurationSource:
    #defaultFileName: application.yml
            